CREATE TABLE IF NOT EXISTS TB_MEMBER (
    MEMBER_ID VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    BIRTH_DATE VARCHAR(8),
    ROLE VARCHAR(20) DEFAULT 'ROLE_USER',
    USE_YN CHAR(1) DEFAULT 'Y',
    REG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CHG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_MEMBER PRIMARY KEY (MEMBER_ID)
);

COMMENT ON TABLE TB_MEMBER IS '회원 정보';
COMMENT ON COLUMN TB_MEMBER.MEMBER_ID IS '회원 ID';
COMMENT ON COLUMN TB_MEMBER.PASSWORD IS '비밀번호';
COMMENT ON COLUMN TB_MEMBER.NAME IS '이름';
COMMENT ON COLUMN TB_MEMBER.BIRTH_DATE IS '생년월일(YYYYMMDD)';
COMMENT ON COLUMN TB_MEMBER.ROLE IS '권한';
COMMENT ON COLUMN TB_MEMBER.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_MEMBER.REG_DT IS '등록일시';
COMMENT ON COLUMN TB_MEMBER.CHG_DT IS '수정일시';

-- 먹은 음식 기록 테이블
CREATE TABLE IF NOT EXISTS TB_FOOD_RECORD (
    RECORD_ID BIGSERIAL NOT NULL,
    RECORD_DATE VARCHAR(8) NOT NULL,
    USER_ID VARCHAR(20) NOT NULL,
    FOOD_ID NUMERIC,
    FOOD_LIST TEXT,
    REG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CHG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_FOOD_RECORD PRIMARY KEY (RECORD_ID)
);

COMMENT ON TABLE TB_FOOD_RECORD IS '먹은 음식 기록';
COMMENT ON COLUMN TB_FOOD_RECORD.RECORD_ID IS '기록 ID';
COMMENT ON COLUMN TB_FOOD_RECORD.RECORD_DATE IS '날짜(YYYYMMDD)';
COMMENT ON COLUMN TB_FOOD_RECORD.USER_ID IS '유저 아이디';
COMMENT ON COLUMN TB_FOOD_RECORD.FOOD_ID IS '음식 아이디';
COMMENT ON COLUMN TB_FOOD_RECORD.FOOD_LIST IS '음식 리스트';
COMMENT ON COLUMN TB_FOOD_RECORD.REG_DT IS '등록일시';
COMMENT ON COLUMN TB_FOOD_RECORD.CHG_DT IS '수정일시';
